<?php
/**
 * Created by PhpStorm.
 * User: Uroaming
 * Date: 2019/4/19
 * Time: 16:09
 */
namespace app\mobile\controller;
use app\admin\model\ApplyRecharge;
use app\admin\model\UserCurrencyAccount;
use app\user\model\UserCurrencyList;
use think\Db;

class Wallet extends Common {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = session('user.id');
    }

    //用户资产首页
    public function index()
    {

        //获取用户账号信息
        $user_account = Db::name('user_currency_account')->where(['user_id' => $this->uid])->find();
        //获取阿美币信息
        $amei_info = Db::name('currency_list')->where(['en_name' => 'AMB'])->find();
        $this->assign('user_account', $user_account);
        $this->assign('amei_info', $amei_info);
        return $this->fetch('index');

    }

    //提现
    public function withdraw()
    {

        $user_info = session('user');
        $bank = db('Bank')->order('id ASC')->select(); //银行列表
        $cash_method = ApplyRecharge::$cash_method; //提现方式
        $bonus_set = db('bonus_ext_set')->where('id',1)->find(); //提现设置
        $trade_account = UserCurrencyAccount::where(['user_id' => $this->uid])->value('transaction_num');  //用户交易账户余额
        $bank_name = Db::name('bank')->where(['id' => $user_info['bank_id']])->value('bank_name');
        $this->assign('cash_method', $cash_method);
        $this->assign('bank_list', $bank);
        $this->assign('bank_name', $bank_name);
        $this->assign('bonus_set', $bonus_set);
        $this->assign('trade_account', $trade_account);
        $this->assign('user_info', $user_info);
        return $this->fetch('withdraw');
    }



}
